services:
  controller:
    build: .
    container_name: controller-service
    ports:
      - 80:80

  #Recommender
  recommender-service: 
    build: ./recommender/RecommenderService
    container_name: recommender-service
    ports:
      - 8001:80

  recommender-database:
    image: mysql
    container_name: mysql_recommender
    environment:
      MYSQL_ROOT_PASSWORD: duper
      MYSQL_DATABASE: recommender_db
    ports:
      - 3309:3306
    volumes:
      - ./recommender/mysql_db_data:/var/lib/mysql
      - ./recommender/entry:/docker-entrypoint-initdb.d/


  # Activity
  activity-service: 
    build: ./activity/ActivityService
    container_name: activity-service
    ports:
      - 8002:80

  activity-database:
    image: mysql
    container_name: activity_database
    environment:
      MYSQL_ROOT_PASSWORD: super
      MYSQL_DATABASE: activity_db
    ports:
      - 3308:3306
    volumes:
      - ./activity/mysql_db_data:/var/lib/mysql
      - ./activity/entry:/docker-entrypoint-initdb.d/ 
  
  # usermanager
  usermanager-service: 
    build: ./usermanager/UserManager
    container_name: usermanager-service
    ports:
      - 8003:80

  usermanager-database:
    image: mysql
    container_name: usermanager_database
    environment:
      MYSQL_ROOT_PASSWORD: fuper
      MYSQL_DATABASE: usermanager_db
    ports:
      - 3307:3306
    volumes:
      - ./usermanager/UserManager/mysql_db_data:/var/lib/mysql
      - ./usermanager/UserManager/entry:/docker-entrypoint-initdb.d/ 
